### ISSUE TITLE
Reach Reports

### ISSUE THREAD

**Issue by juanchi-mdo** [google/argon#11]
I've seen there was an issue related to this but was closed as no answer was given and I'd like to re open the discussion cause I'm having the same problem.

_"The POST works and a table is created with the correct header/files but there is no data inserted into the table.

Have tried this on a few Reach reports with the same issue and confirmed there is indeed data with both single and multiple file flag enabled."_

I can confirm the service account has access to the report and I can see the File ID's being processed in the logs. I guess the problem has to do with the last couple lines of the reports where it says "Grand Total" and the 2 following lines, which makes the function "crash" when it compares the schema to the one in BQ and therefore it doesn't ingests any data.

Please see attached a screenshot of the reach reports last lines and the error in the CF logs.

<img width="904" alt="Captura de Pantalla 2022-01-12 a la(s) 11 10 29" src="https://user-images.githubusercontent.com/80838156/149155982-c9416e62-4b7a-4570-b9fe-7ea55076a7d9.png">

<img width="1016" alt="Captura de Pantalla 2022-01-12 a la(s) 11 23 16" src="https://user-images.githubusercontent.com/80838156/149158133-4624fbb9-27df-4253-8ec9-b3ba528cfda8.png">

**Comment by achembarpu** [comment]
Hi juanchi-mdo, Thanks for your feedback. Could you email me at achembarpu@google.com, with more details? Happy to debug this further. Cheers!

**Comment by aponbas** [comment]
I just want to add that we're running into the same issue with Reach reports in Campaign Manager. Standard reports work fine, but Reach reports can not be run by Argon, and also do not return an error.

**Comment by achembarpu** [comment]
Quick update here, I aiming to release a new version in Q3 that will solve for this issue. Thanks for your patience!

**Comment by achembarpu** [comment]
Hi @juanchi-mdo, Argon is now deprecated as both [DV360](https://support.google.com/displayvideo/answer/6375151) and [CM360](https://support.google.com/campaignmanager/answer/2823849) natively support exporting reports to BQ. Do try them out and let us know if they work for your usecase. Thanks!
