### ISSUE TITLE
ERROR: Provide DCM Profile ID and Account Email ID.

### ISSUE THREAD

**Issue by shahid-khattak** [google/argon#2]
I have deployed the app, however, calls to the service with cloud scheduler keep on failing with the following error.
`ERROR: Provide DCM Profile ID and Account Email ID.` 
I put some logging in place to see what payload is actually received in App Engine, that shows null (mind you I do send the request with body as mentioned in the instructions).
I am pretty certain that all the requirements for this app to run are in place. Has anybody else got this app to work?

**Comment by shahid-khattak** [comment]
p.s. it works from Postman, but not from cloud scheduler.

**Comment by achembarpu** [comment]
Thanks for reporting this! This appears to be a regression in the cloud scheduler UI, we are working on it.
In the meanwhile, you can schedule it via the API or switch to a normal HTTP trigger in the UI. I have updated the repo code to accomodate for this.

**Comment by shahid-khattak** [comment]
Another point: This connector assumes that the report has run and there's .csv file for it. Can it be included that it checks if there's a file, if not then run the report first, produce the .csv and then download it to BQ?

**Comment by achembarpu** [comment]
The current focus of argon is to leave the report running to DCM, and use this only as a connector. A suggestion would be to schedule the service to run more often (maybe hourly).

**Comment by achembarpu** [comment]
This issue has been resolved on Cloud Scheduler - POST body contents should be stored correctly now. Could you confirm?

**Comment by shahid-khattak** [comment]
Yes, can confirm that it is working now. Thank you

**Comment by achembarpu** [comment]
Thanks!
