### ISSUE TITLE
Cannot read property 'isValid' of undefined

### ISSUE THREAD

**Issue by shahid-khattak** [google/argon#3]
There's a report file (in csv) available, however the data.items is always empty (see it after putting some logging in place), and it throws this error.
`Cannot read property 'isValid' of undefined`.
It happens in the very first condition of for loop.

`      for (const item of data.items) {
        if (item.status.match(REPORT_AVAIL_PATTERN)) {
          const reportDate = item.dateRange.endDate;
          if (reportDate in lookbackDates) {
            reportFiles[item.id] = item;
            delete lookbackDates[reportDate]; // remove found dates
          }
          latestDate = DateTime.fromFormat(reportDate, DATE_FORMAT);
        }
      }`

What are we missing here?

**Comment by achembarpu** [comment]
Could you confirm that this is indeed the case even on commit https://github.com/google/argon/commit/8b65acc9354ae809db220aabeca978c87de7e6ad?

**Comment by shahid-khattak** [comment]
Yes, that's correct.

**Comment by achembarpu** [comment]
This issue should be fixed in https://github.com/google/argon/commit/df4635f3bb47745202130cdb372b28b23f3554d1. Could you confirm?

**Comment by shahid-khattak** [comment]
Improved logging indeed, but It still skips reading/parsing the actual reports in DCM. I will send you logs separately.

**Comment by achembarpu** [comment]
Closing, as the code-related issue has been fixed.
