### ISSUE TITLE
500 error on API connection

### ISSUE THREAD

**Issue by knuthelge** [google/argon#4]
Long time watcher, first time caller! 

This project would ease my workload a lot setting up our internal reporting, so hoping to get some pointers for getting it working. All help is appreciated :)

I've tried to set up Argon based on the setup guide, but are hitting a wall when running the function (500 error on API). My goal is to set up some automated DV360 reports to BQ, for use in Data Studio. 

**Things I've done:**
- I've created the service account, set it up with our DV360 account (reporting only), created a report, and shared it with the service account (link). 
- Enabled DBM and DCM/DFA API's in the GCP project (The API console reports requests to DBM API)
- Set up the dataset
- Deployed the cloud function without errors. 
- Set up at scheduler based on the instructions. 
- Tried to trigger the scheduler, but it failed.
- Tried to repeat everything a couple of times. 

**The result I get**
So I went into the testing tab on the cloud function, tried to use the same triggering event to trace what could be wrong. The code seems to go through the steps ok until it hits the API client where it gets a 500 error. See the attached images. 

What could I be missing?

![Skjermbilde 2020-03-26 kl  16 08 12](https://user-images.githubusercontent.com/3678946/77663512-6ee02580-6f7d-11ea-88f1-6d17ed955a63.png)
![Skjermbilde 2020-03-26 kl  16 03 18](https://user-images.githubusercontent.com/3678946/77663520-71427f80-6f7d-11ea-9845-eaaa5bf36b30.png)

**Comment by knuthelge** [comment]
I identified my error. I didn't find any files to pull in.

**Comment by paulakcelrod** [comment]
Hello @knuthelge , how did you fix the error ? It seems that I've got the same error as you

**Comment by achembarpu** [comment]
@paulakcelrod - Are you facing this error at the same stage? Do check your logs for the exact step.
If so, it can indeed be caused by either not having the right permissions to fetch files, or no files being present, for that report.

**Comment by knuthelge** [comment]
Hi @paulakcelrod. If I remember correctly the report hadn't generated any files yet, resulting in no files being present. If you make sure the permissions are correct and at least one file generated, as @achembarpu commented, it should work as expected. Been running flawlessly ever since.

**Comment by paulakcelrod** [comment]
Hello @achembarpu, @knuthelge  yes thanks! Everything works fine now
