### ISSUE TITLE
Reach Reports

### ISSUE THREAD

**Issue by fayious** [google/argon#5]
The POST works and a table is created with the correct header/files but there is no data inserted into the table.

Have tried this on a few Reach reports with the same issue and confirmed there is indeed data with both single and multiple file flag enabled.

**Comment by achembarpu** [comment]
Hi @fayious ,

Thanks for opening this issue. Apologies for the delayed response, I was out of office and missed this.
Could you confirm that the service account has access to the report, from the time that the files were generated? Moreover, do you see the File IDs being processed in the logs?

Thanks!

**Comment by achembarpu** [comment]
Closing as stale issue.
