### ISSUE TITLE
Matching data between CM and DV

### ISSUE THREAD

**Issue by paulakcelrod** [google/argon#9]
Hi,
Thanks for the sharing !

Do you know which SQL query would work in order to match CM and DV data ?
Taking for example that the Placement Name CM and the Line Item DV would be the same so that the data match.
Thanks

**Comment by achembarpu** [comment]
Hi Paul,

Thanks for using Argon! Unfortunately, this question is out-of-scope for Argon. Please reach out to Product/Customer Support at Google, for these type of requests. Thanks!
